swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
 
  
  /user/transactions/{UsertransactionsID}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User Transactions
      description: API for checking user transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
        - name: UsertransactionsID
          in: path
          description: User's transactions
          type: integer
          required: true
      produces:   
        - application/json
      responses:
        '200':
          description: User's transactions 
          schema:
            $ref: '#/definitions/Usertransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
          
  
  
  /user/transactions/{UsertransactionsID}/{TransactionID}:        
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module 
      summary: Detail Transaction
      description: Api transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
        - name: UsertransactionsID
          in: path
          description: User's transactions
          type: integer
          required: true
        - name: TransactionID
          in: path
          description: User's transaction details
          type: integer
          required: true
      produces:
       - application/json
      responses:
        '200':
          description: transaction detail
          schema:
            $ref: '#/definitions/TransactionID' 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error    
   
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module 
      summary: Detail Transaction
      description: Api transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
        - name: UsertransactionsID
          in: path
          description: User's transactions
          type: integer
          required: true
        - name: TransactionID
          in: path
          description: User's transaction details
          type: integer
          required: true
        - name: body
          in: body
          description: new transaction detail
          required: true
          schema:
            $ref: '#/definitions/TransactionInformation'
      produces:
       - application/json
      responses:
        '200':
          description: Successful new details of the transaction
          schema:
            $ref: '#/definitions/ApiResponseTransactionInformation' 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error      
          
    
    put:       
      security:
        - Bearer: []
      tags:
        - Transactions Module 
      summary: Detail Transaction
      description: Api transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
        - name: UsertransactionsID
          in: path
          description: User's transactions
          type: integer
          required: true
        - name: TransactionID
          in: path
          description: User's transaction details
          type: integer
          required: true
        - name: body
          in: body
          description: Update transaction detail
          required: true
          schema:
            $ref: '#/definitions/TransactionInformation'
      produces:
       - application/json
      responses:
        '200':
          description: Successful transaction detail modification
          schema:
            $ref: '#/definitions/ApiResponseTransactionInformation' 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error    
     
     
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module 
      summary: Detail Transaction
      description: Api transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
        - name: UsertransactionsID
          in: path
          description: User's transactions
          type: integer
          required: true
        - name: TransactionID
          in: path
          description: User's transaction details
          type: integer
          required: true
      produces:
       - application/json
      responses:
        '200':
          description: Successful removed transaction detail
          schema:
            $ref: '#/definitions/ApiResponseRemoved' 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    
    
    
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
        
  Usertransactions:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amout:
        type: integer
      balence:
        type: integer
  TransactionID:
    type: object
    properties:
      Transaction Type:
        type: string
      Category:
        type: string
      Notes:
        type: string
        
  TransactionInformation:
    type: object
    properties:
      Category:
        type: string
      Notes:
        type: string
        
  ApiResponseTransactionInformation:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          Category:
            type: string
          Notes:
            type: string
  
  ApiResponseRemoved:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
 
    
  
  
  
  
  
  