swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
 
  
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: API User accounts
      description: API for fetching a user accounts (route to fetch the user's accounts)
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
      produces:   
        - application/json
      responses:
        '200':
          description: User's transactions 
          schema:
            $ref: '#/definitions/AccountUser'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
          
  
  
  /user/account/{id}/transactions:        
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module 
      summary: API User transactions
      description: API retrieving all user transactions according to the chosen account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
        - name: id
          in: path
          description: User's account id
          type: integer
          required: true
          
      produces:
       - application/json
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/AllTransactions' 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error   
          
          
          
  /user/account/{id}/transactions/{transactionId}:  
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module 
      summary: API User transactions
      description: API fetching a single user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
        - name: id
          in: path
          description: User's account id
          type: integer
          required: true
        - name: transactionId
          in: path
          description: User's transactions id
          type: integer
          required: true
      produces:
       - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/Transaction' 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error      
          
    post:       
      security:
        - Bearer: []
      tags:
        - Transactions Module 
      summary: API User transactions
      description: API add a single user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
        - name: id
          in: path
          description: User's account id
          type: integer
          required: true
        - name: transactionId
          in: path
          description: User's transactions id
          type: integer
          required: true
        - name: body
          in: body
          description: new transaction detail
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
       - application/json
      responses:
        '200':
          description: Successful new details of the transaction
          schema:
            $ref: '#/definitions/ApiResponsePost' 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error       
     
     
    put:       
      security:
        - Bearer: []
      tags:
        - Transactions Module 
      summary: API User transactions
      description: API edit a single user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
        - name: id
          in: path
          description: User's account id
          type: integer
          required: true
        - name: transactionId
          in: path
          description: User's transactions id
          type: integer
          required: true
        - name: body
          in: body
          description: edit transaction detail
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
       - application/json
      responses:
        '200':
          description: Successful edit details of the transaction
          schema:
            $ref: '#/definitions/ApiResponsePut' 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error    
     
     
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module 
      summary: Detail Transaction
      description: Api transaction details (route to delete user transaction details)
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JTW token
          type: string
          required: true
        - name: id
          in: path
          description: User's account id
          type: integer
          required: true
        - name: transactionId
          in: path
          description: User's transactions id
          type: integer
          required: true
      produces:
       - application/json
      responses:
        '200':
          description: Successful removed transaction detail
          schema:
            $ref: '#/definitions/ApiResponseRemoved' 
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    
    
    
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
        
  AccountUser:
    type: object
    properties:
      accounts:
        type: array
        items:
          type: object
          properties:
            Id:
              type: number
            Title:
              type: string
            Balance:
              type: string
            Description:
              type: string
  AllTransactions:
    type: object
    properties:
      transactions:
        type: array
        items:
          type: object
          properties:
            TransactionsId:
              type: number
            Date:
              type: string
            Description:
              type: string
            Amount:
              type: number
            Balance:
              type: number
            Type:
              type: string
            Category:
              type: string
            Notes:
              type: string
        
  Transaction:
    type: object
    properties:
      TransactionsId:
        type: number
      Date:
        type: string
      Description:
        type: string
      Amount:
        type: number
      Balance:
        type: number
      Type:
        type: string
      Category:
        type: string
      Notes:
        type: string
        
  ApiResponsePost:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          TransactionsId:
            type: number
          Date:
            type: string
          Description:
            type: string
          Amount:
            type: number
          Balance:
            type: number
          Type:
            type: string
          Category:
            type: string
          Notes:
            type: string
            
  ApiResponsePut:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          Category:
            type: string
          Notes:
            type: string
  
  ApiResponseRemoved:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
 
    
  
  
  
  
  
  